export const assets = {
  logoCompact: new URL("../../assets/brand/logo/horsh-logo-compact.png", import.meta.url).href,
  bgPortal: new URL("../../assets/images/backgrounds/bg-portal-platform.webp", import.meta.url).href,
  bgCards: new URL("../../assets/images/backgrounds/bg-card-slots.webp", import.meta.url).href,
  bgFactory: new URL("../../assets/images/backgrounds/bg-factory-line.webp", import.meta.url).href,
  bgToastLab: new URL("../../assets/images/backgrounds/bg-toast-lab.webp", import.meta.url).href,
  bgTerminal: new URL("../../assets/images/backgrounds/bg-terminal-corridor.webp", import.meta.url).href,
  homePlatform: new URL("../../assets/images/home/home-platform-optimized.webp", import.meta.url).href,
  homeMascot: new URL("../../assets/images/home/home-mascot.webp", import.meta.url).href,
  homePanelOnline: new URL("../../assets/images/home/home-panel-online.webp", import.meta.url).href,
  homePanelPlan: new URL("../../assets/images/home/home-panel-plan.webp", import.meta.url).href,
  homePanelBread: new URL("../../assets/images/home/home-panel-bread.webp", import.meta.url).href,
  homePanelScan: new URL("../../assets/images/home/home-panel-scan.webp", import.meta.url).href,
  homePanelComplete: new URL("../../assets/images/home/home-panel-complete.webp", import.meta.url).href,
  mascotField: new URL("../../assets/images/mascot/mascot-field-agent_attr1_subject.webp", import.meta.url).href,
  mascotOperator: new URL("../../assets/images/mascot/mascot-operator-terminal-v7-optimized.webp", import.meta.url).href,
  factoryCutout: new URL("../../assets/images/factory/haoshi-transparent-factory-cutout-optimized.webp", import.meta.url).href,
  ingredientMixer: new URL("../../assets/images/ingredient/mixing-core-transparent.webp", import.meta.url).href,
  ingredientCardGluten: new URL("../../assets/images/ui/图层 1.webp", import.meta.url).href,
  ingredientCardYeast: new URL("../../assets/images/ui/图层 2.webp", import.meta.url).href,
  ingredientCardWheat: new URL("../../assets/images/ui/图层 3.webp", import.meta.url).href,
  ingredientCardQuinoa: new URL("../../assets/images/ui/图层 4.webp", import.meta.url).href,
  bakingOven: new URL("../../assets/images/baking/oven-cavity.webp", import.meta.url).href,
  toastDough: new URL("../../assets/images/baking/toast-dough.webp", import.meta.url).href,
  toastRaw: new URL("../../assets/images/baking/toast-raw.webp", import.meta.url).href,
  toastOverdone: new URL("../../assets/images/baking/toast-overdone.webp", import.meta.url).href,
  heatThumb: new URL("../../assets/images/baking/heat-thumb-yellow.webp", import.meta.url).href,
  heatTrack: new URL("../../assets/images/baking/heat-temperature-track.webp", import.meta.url).href,
  proofingChamber: new URL("../../assets/images/proofing/proofing-chamber-transparent.webp", import.meta.url).href,
  proofingSliderTrack: new URL("../../assets/images/proofing/proofing-slider-track-marked.webp", import.meta.url).href,
  proofingMarkerLow: new URL("../../assets/images/proofing/slider-marker-low-green.webp", import.meta.url).href,
  proofingMarkerIdeal: new URL("../../assets/images/proofing/slider-marker-ideal-yellowgreen.webp", import.meta.url).href,
  proofingMarkerHigh: new URL("../../assets/images/proofing/slider-marker-deviated-orange.webp", import.meta.url).href,
  packageModel: new URL("../../assets/models/bread-package-optimized-lite.glb", import.meta.url).href,
  productBoxCropped: new URL("../../assets/product/quinoa-toast/box-420g-3d-cropped.webp", import.meta.url).href,
  productFrontCropped: new URL("../../assets/product/quinoa-toast/pouch-front-cropped.webp", import.meta.url).href
};
