create table if not exists public.h5_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  client_time timestamptz,
  event_name text not null,
  session_id text not null,
  order_id text,
  page text,
  bug_id text,
  bug_type text,
  description text,
  stage text,
  progress numeric,
  source_host text,
  pathname text,
  user_agent text,
  viewport text,
  data jsonb not null default '{}'::jsonb
);

create index if not exists h5_events_created_at_idx on public.h5_events (created_at desc);
create index if not exists h5_events_session_id_idx on public.h5_events (session_id);
create index if not exists h5_events_event_name_idx on public.h5_events (event_name);

alter table public.h5_events enable row level security;
